In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
print(a)

[1 2 3]


In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(3,)

In [9]:
b = np.array([[1,2,3],[4,5,6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b.shape

(2, 3)

In [12]:
c1 = np.array([0,1,2,3,4,5])
c1

array([0, 1, 2, 3, 4, 5])

In [13]:
c2 = c1.reshape((2,3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [16]:
c4 = c2.flatten() #copyを返す
c4

array([0, 1, 2, 3, 4, 5])

In [17]:
a.dtype

dtype('int32')

In [18]:
d = np.array([1,2],dtype=np.int16)
d

array([1, 2], dtype=int16)

In [19]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

In [20]:
a

array([1, 2, 3])

In [21]:
a[0]

1

In [22]:
a[1:]

array([2, 3])

In [23]:
a[-1]

3

In [24]:
b[0]

array([1, 2, 3])

In [25]:
b[1,0]

4

In [27]:
b[:,2]

array([3, 6])

In [28]:
b[1,:]

array([4, 5, 6])

In [29]:
b[0,1:]

array([2, 3])

In [31]:
b[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [32]:
a

array([1, 2, 3])

In [33]:
a[2] = 4
a

array([1, 2, 4])

In [34]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
b[1,2] = 7
b

array([[1, 2, 3],
       [4, 5, 7]])

In [36]:
b[:,2]=8
b

array([[1, 2, 8],
       [4, 5, 8]])

In [37]:
a1 = a
a1

array([1, 2, 4])

In [38]:
a1[1]= 5
a1

array([1, 5, 4])

In [39]:
a

array([1, 5, 4])

In [53]:
a2 = a.copy()
a2

array([1, 5, 4])

In [65]:
a2[0]=6
a2

array([6, 5, 4])

In [66]:
a

array([1, 5, 4])

In [67]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [68]:
c3 = c2.ravel()
c4 = c2.flatten()
c3[0] = 6
c4[1] = 7

In [69]:
c3

array([6, 1, 2, 3, 4, 5])

In [70]:
c4

array([0, 7, 2, 3, 4, 5])

In [71]:
c2

array([[6, 1, 2],
       [3, 4, 5]])

In [73]:
py_list1 = [0,1]
py_list2 = py_list1[:]
py_list2[0] = 2
print(py_list1)
print(py_list2)

[0, 1]
[2, 1]


In [76]:
np_array1 = np.array([0,1])
np_array2 = np_array1[:]
np_array2[0] = 2
print(np_array1)
print(np_array2)

[2 1]
[2 1]


In [78]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [82]:
f = np.random.random((3,2))
f

array([[0.7876344 , 0.60407517],
       [0.33369009, 0.58170337],
       [0.27054024, 0.23606813]])

In [85]:
np.random.seed(123)
np.random.random((3,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646]])

In [86]:
np.random.seed(123)
np.random.random((4,2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [88]:
np.random.seed(123)
np.random.randint(1,10)

3

In [90]:
np.random.seed(123)
np.random.randint(1,10,(3,3))

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [93]:
np.random.seed(123)
np.random.uniform(0.0,5.0,size=(2,3))

array([[3.48234593, 1.43069667, 1.13425727],
       [2.75657385, 3.59734485, 2.1155323 ]])

In [94]:
np.random.seed(123)
np.random.uniform(size=(4,3))

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971]])

In [95]:
np.random.seed(123)
np.random.randn(4,2)

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263]])

In [96]:
np.zeros(3)

array([0., 0., 0.])

In [97]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [98]:
np.ones(2)

array([1., 1.])

In [99]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [101]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
np.full(3,3.14)

array([3.14, 3.14, 3.14])

In [103]:
np.full((2,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [104]:
np.nan

nan

In [105]:
np.array([1,2,np.nan])

array([ 1.,  2., nan])

In [107]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [108]:
np.linspace(0,np.pi,21)

array([0.        , 0.15707963, 0.31415927, 0.4712389 , 0.62831853,
       0.78539816, 0.9424778 , 1.09955743, 1.25663706, 1.41371669,
       1.57079633, 1.72787596, 1.88495559, 2.04203522, 2.19911486,
       2.35619449, 2.51327412, 2.67035376, 2.82743339, 2.98451302,
       3.14159265])

In [110]:
I = np.array([2,2,6,1,3])
np.diff(I)

array([ 0,  4, -5,  2])

In [111]:
print(a)
print(a1)

[1 5 4]
[1 5 4]


In [112]:
np.concatenate([a,a1])

array([1, 5, 4, 1, 5, 4])

In [113]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [115]:
b1 = np.array([[10],[20]])
b1

array([[10],
       [20]])

In [116]:
np.concatenate([b,b1],axis=1)

array([[ 1,  2,  8, 10],
       [ 4,  5,  8, 20]])

In [117]:
b2 = np.array([30,60,45])
b2

array([30, 60, 45])

In [118]:
b3 = np.vstack([b,b2])
b3

array([[ 1,  2,  8],
       [ 4,  5,  8],
       [30, 60, 45]])

In [120]:
first,second = np.hsplit(b3,[2])

In [121]:
first

array([[ 1,  2],
       [ 4,  5],
       [30, 60]])

In [124]:
second

array([[ 8],
       [ 8],
       [45]])

In [127]:
first1,second1 = np.vsplit(b3,[2])

In [128]:
first1

array([[1, 2, 8],
       [4, 5, 8]])

In [129]:
second1

array([[30, 60, 45]])

In [130]:
b

array([[1, 2, 8],
       [4, 5, 8]])

In [131]:
b.T

array([[1, 4],
       [2, 5],
       [8, 8]])

In [132]:
a

array([1, 5, 4])

In [133]:
a[np.newaxis,:]

array([[1, 5, 4]])

In [134]:
a[:,np.newaxis]

array([[1],
       [5],
       [4]])

In [135]:
m = np.arange(0,4)
m

array([0, 1, 2, 3])

In [137]:
n = np.arange(4,7)
n

array([4, 5, 6])

In [138]:
xx,yy = np.meshgrid(m,n)
xx

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [139]:
yy

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [1]:
a = np.arange(3)
b = np.arange(-3,3).reshape((2,3))
c = np.arange(1,7).reshape((2,3))
d = np.arange(6).reshape((3,2))
e = np.linspace(-1,1,10)
print("a:",a)
print("b:",b)
print("c:",c)
print("d:",d)
print("e:",e)


NameError: name 'np' is not defined